Correct includes value in library.properties
The includes field in library.properties is used to specify which #include directives should be added to the sketch via Sketch > Include Library > WolkConnect. The previous value caused compilation to fail:

error: src/WolkConn.h: No such file or directory

 #include <src/WolkConn.h>

Reference:
https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#libraryproperties-file-format